services:
  bot:
    build: .
    environment:
      - BOT_TOKEN
      - API_ID
      - API_HASH
      - OWNER_ID
      - ARIA2_RPC_SECRET
      - MONGO_URI
      - MONGO_DB_NAME
    restart: unless-stopped
    volumes:
      - downloads:/app/downloads
      - encoded:/app/encoded
      - thumbnails:/app/thumbnails

volumes:
  downloads:
  encoded:
  thumbnails:
